apiVersion: v1
kind: Service
metadata:
  labels:
    com.docker.deploy-namespace: docker
    com.docker.fry: compose.api
    com.docker.image-tag: latest
  name: compose-api
  namespace: docker
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    com.docker.deploy-namespace: docker
    com.docker.fry: compose.api
    com.docker.image-tag: latest
  sessionAffinity: None
  type: ClusterIP
