apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: compose-stack-view
rules:
- apiGroups:
  - compose.docker.com
  resources:
  - stacks
  - stacks/scale
  - stacks/log
  - stacks/composeFile
  verbs:
  - get
  - list
  - watch
